### ISSUE TITLE
How to vacuum pg_class relation

### ISSUE THREAD

**Issue by cobolbaby** [gpdbkr/GreenplumUtil#2]
When I vacuum full the system tables, there are several system tables that is failed to eliminate the bloat, such as pg_class. How can I solve it? Can you give me some suggestions

![2020-03-10 23-23-29屏幕截图](https://user-images.githubusercontent.com/11460848/76337762-c9994080-6332-11ea-88d7-86af20ec698c.png)

**Comment by gpdbkr** [comment]
My suggestion step:

1. run vaucuum full pg_catalog.pg_class not vacuum 
While running vacuum full pg_catalog.pg_class, database is hang because of ACCESS EXCLUSIVE LOCK of catalog table.
https://gpdb.docs.pivotal.io/6-4/admin_guide/dml.html 

You need to run vacuum full it once.
 1) modify DBNAME of vacuum_full_analyze.sh from testdb to what you use database name
 2) run  "sh vacuum_full_analyze.sh" 
 
2. Register cron_vacuum_analyze.sh to crontab
It would prevent table bloat next time.
# DB Vacuum analyze
00 00 * * * /data/dba/utilities/cron_vacuum_analyze.sh &

**Comment by cobolbaby** [comment]
Sorry, the instruction I executed is vacuum full.

**Comment by gpdbkr** [comment]
The gp_bloat_diag shows bloated table list using statistical information.
So, after executing Vacuum full,  you need to run "analyze".

Even though you executed vacuum full and analyze pg_class, if the table size was not reduced,  you should get in touch Pivotal Support team.

**Comment by cobolbaby** [comment]
Ref: https://askgp.chapterx.cn/topic/67/how-to-vacuum-pg_class-relation
